[idris2]
version = "0.6.0"
url     = "https://github.com/idris-lang/Idris2"
commit  = "main"

[db.algebra]
type = "github"
url  = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "main"
ipkg = "algebra.ipkg"
test = "test/test.ipkg"

[db.ansi]
type = "github"
url  = "https://github.com/idris-community/idris2-ansi"
commit = "main"
ipkg = "ansi.ipkg"

[db.apache-mime-types]
type = "github"
url  = "https://github.com/kbertalan/idris2-apache-mime-types"
commit = "main"
ipkg = "apache-mime-types.ipkg"

[db.array]
type = "github"
url  = "https://github.com/stefan-hoeck/idris2-array"
commit = "main"
ipkg = "array.ipkg"
test = "test/test.ipkg"

[db.barbies]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-barbies"
commit = "main"
ipkg   = "barbies.ipkg"

[db.bounded-doubles]
type   = "github"
url    = "https://github.com/buzden/idris2-bounded-doubles"
commit = "master"
ipkg   = "bounded-doubles.ipkg"
test   = "tests/library-tests.ipkg"

[db.bounded-doubles-hedgehog-generators]
type   = "github"
url    = "https://github.com/buzden/idris2-bounded-doubles"
commit = "master"
ipkg   = "hedgehog-generators.ipkg"
test   = "tests/generators-tests.ipkg"

[db.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "main"
ipkg   = "bytestring.ipkg"

[db.collie]
type   = "github"
url    = "https://github.com/ohad/collie"
commit = "main"
ipkg   = "collie.ipkg"

[db.comonad]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-comonad"
commit = "main"
ipkg   = "comonad.ipkg"

[db.coop]
type   = "github"
url    = "https://github.com/buzden/idris2-coop"
commit = "master"
ipkg   = "coop.ipkg"
test   = "tests/tests.ipkg"

[db.crypt]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-crypt"
commit = "main"
ipkg   = "crypt.ipkg"
test   = "test/test.ipkg"

[db.dinwiddy]
type   = "github"
url    = "https://github.com/bobbbay/dinwiddy"
commit = "main"
ipkg   = "dinwiddy.ipkg"

[db.dom]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-dom"
commit = "main"
ipkg   = "dom.ipkg"

[db.dom-mvc]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-dom-mvc"
commit = "main"
ipkg   = "dom-mvc.ipkg"

[db.dot-gv]
type   = "github"
url    = "https://github.com/CodingCellist/idris2-dot-parse"
commit = "main"
ipkg   = "dot-parse.ipkg"

[db.eff]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-eff"
commit = "main"
ipkg   = "eff.ipkg"

[db.effect]
type   = "github"
url    = "https://github.com/Russoul/Idris2-Effect"
commit = "master"
ipkg   = "effect.ipkg"

[db.elab-pretty]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-pretty.ipkg"

[db.elab-util]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "main"
ipkg   = "elab-util.ipkg"

[db.filepath]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-filepath"
commit = "main"
ipkg   = "filepath.ipkg"
test   = "test/test.ipkg"

[db.finite]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-finite"
commit = "main"
ipkg   = "finite.ipkg"
test   = "test/test.ipkg"

[db.fix-whitespace]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris-fix-whitespace"
commit = "main"
ipkg   = "fix-whitespace.ipkg"

[db.freer]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-freer"
commit = "main"
ipkg   = "freer.ipkg"

[db.fvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-fvect"
commit = "main"
ipkg   = "fvect.ipkg"

[db.getopts]
type = "github"
url  = "https://github.com/idris-community/idris2-getopts"
commit = "main"
ipkg = "getopts.ipkg"

[db.graph]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-graph"
commit = "main"
ipkg   = "graph.ipkg"
test   = "test/test.ipkg"

[db.golden-runner-helper]
type   = "github"
url    = "https://github.com/buzden/idris2-golden-runner-helper"
commit = "master"
ipkg   = "golden-runner-helper.ipkg"
test   = "tests/tests.ipkg"

[db.hashable]
type   = "github"
url    = "https://github.com/Z-snails/Idris2-hashable"
commit = "main"
ipkg   = "hashable.ipkg"

[db.hashmap]
type   = "github"
url    = "https://github.com/Z-snails/idris2-hashmap"
commit = "main"
ipkg   = "hashmap.ipkg"

[db.hedgehog]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "main"
ipkg   = "hedgehog.ipkg"

[db.idrall]
type   = "github"
url    = "https://github.com/alexhumphreys/idrall"
commit = "main"
ipkg   = "idrall.ipkg"

[db.idris2-go]
type        = "github"
url         = "https://github.com/kbertalan/idris2-go"
commit      = "main"
ipkg        = "idris2-go.ipkg"
packagePath = true

[db.idris2-go-lib]
type   = "github"
url    = "https://github.com/kbertalan/idris2-go"
commit = "main"
ipkg   = "idris2-go-lib.ipkg"
test   = "tests/libtests.ipkg"

[db.if-unsolved-implicit]
type   = "git"
url    = "https://github.com/buzden/idris2-if-unsolved-implicit"
commit = "master"
ipkg   = "if-unsolved-implicit.ipkg"
test   = "tests/tests.ipkg"

[db.indexed]
type   = "github"
url    = "https://github.com/mattpolzin/idris-indexed"
commit = "main"
ipkg   = "indexed.ipkg"

[db.indexed-graph]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-indexed-graph"
commit = "main"
ipkg   = "indexed-graph.ipkg"

[db.js]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-dom"
commit = "main"
ipkg   = "js/js.ipkg"

[db.json]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-json"
commit = "main"
ipkg   = "json.ipkg"
test   = "test/test.ipkg"

[db.json-simple]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-json"
commit = "main"
ipkg   = "simple/json-simple.ipkg"
test   = "test/test.ipkg"

[db.just-a-monad]
type   = "github"
url    = "https://github.com/Russoul/Just-a-Monad"
commit = "main"
ipkg   = "just-a-monad.ipkg"

[db.katla]
type   = "github"
url    = "https://github.com/idris-community/katla"
commit = "main"
ipkg   = "katla.ipkg"

[db.lana]
type   = "github"
url    = "https://git.sr.ht/~janus/lana"
commit = "master"
ipkg   = "lana.ipkg"

[db.lens]
type   = "github"
url    = "https://github.com/kiana-S/idris2-lens"
commit = "main"
ipkg   = "lens.ipkg"

[db.lsp]
type        = "github"
url         = "https://github.com/idris-community/idris2-lsp"
commit      = "main"
ipkg        = "lsp.ipkg"
packagePath = true

[db.lsp-lib]
type        = "github"
url         = "https://github.com/idris-community/lsp-lib"
commit      = "main"
ipkg        = "lsp-lib.ipkg"

[db.markdown]
type = "github"
url  = "https://github.com/running-grass/idris2-markdown"
commit = "main"
ipkg = "markdown.ipkg"

[db.monocle]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-monocle"
commit = "main"
ipkg   = "monocle.ipkg"

[db.mtl-tuple-impls]
type   = "github"
url    = "https://github.com/buzden/idris2-mtl-tuple-impls"
commit = "master"
ipkg   = "mtl-tuple-impls.ipkg"
test   = "tests/tests.ipkg"

[db.multiplate]
type   = "github"
url    = "https://github.com/Z-snails/multiplate-idr"
commit = "main"
ipkg   = "multiplate.ipkg"
test   = "test/test.ipkg"

# [db.newtype-deriving]
# type   = "github"
# url    = "https://github.com/MarcelineVQ/idris2-newtype-deriving"
# commit = "master"
# ipkg   = "newtype-deriving.ipkg"

[db.ncurses-idris]
type   = "github"
url    = "https://github.com/mattpolzin/ncurses-idris"
commit = "main"
ipkg   = "ncurses-idris.ipkg"

[db.pack]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "main"
ipkg   = "pack.ipkg"

[db.pack-admin]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "main"
ipkg   = "pack-admin.ipkg"

[db.park_bench]
type   = "github"
url    = "https://github.com/Z-snails/park_bench"
commit = "main"
ipkg   = "park_bench.ipkg"

[db.parser]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "parser.ipkg"
test   = "test/test.ipkg"

[db.parser-json]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "json/parser-json.ipkg"
test   = "test/test.ipkg"

[db.parser-show]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "show/parser-show.ipkg"
test   = "test/test.ipkg"

[db.parser-tsv]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "tsv/parser-tsv.ipkg"
test   = "test/test.ipkg"

[db.parser-toml]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "toml/parser-toml.ipkg"
test   = "test/test.ipkg"

[db.parser-webidl]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "main"
ipkg   = "webidl/parser-webidl.ipkg"
test   = "test/test.ipkg"

[db.pg-idris]
type   = "github"
url    = "https://github.com/mattpolzin/pg-idris"
commit = "main"
ipkg   = "pg-idris.ipkg"

[db.prettier]
type   = "github"
url    = "https://github.com/Z-snails/prettier"
commit = "main"
ipkg   = "prettier.ipkg"

[db.prettier-ansi]
type = "github"
url  = "https://github.com/idris-community/idris2-ansi"
commit = "main"
ipkg = "prettier/prettier-ansi.ipkg"

[db.pretty-show]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "main"
ipkg   = "pretty-show.ipkg"
test   = "test/test.ipkg"

[db.prim]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-prim"
commit = "main"
ipkg   = "prim.ipkg"
test   = "test/test.ipkg"

[db.profiler]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-profiler"
commit = "main"
ipkg   = "profiler.ipkg"

[db.profunctors]
type   = "github"
url    = "https://github.com/kiana-S/idris2-profunctors"
commit = "main"
ipkg   = "profunctors.ipkg"

[db.quantifiers-extra]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-quantifiers-extra"
commit = "main"
ipkg   = "quantifiers-extra.ipkg"

[db.qutescript]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-qutescript"
commit = "main"
ipkg   = "qutescript.ipkg"

[db.random-pure]
type   = "git"
url    = "https://github.com/buzden/idris2-random-pure"
commit = "master"
ipkg   = "random-pure.ipkg"
test   = "tests/tests.ipkg"

[db.refined]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "main"
ipkg   = "refined.ipkg"

[db.refined-json]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "main"
ipkg   = "json/refined-json.ipkg"
test   = "test/test.ipkg"

[db.refined-tsv]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "main"
ipkg   = "tsv/refined-tsv.ipkg"
test   = "test/test.ipkg"

[db.rhone]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone"
commit = "main"
ipkg   = "rhone.ipkg"
test   = "test/test.ipkg"

[db.rhone-js]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rhone-js"
commit = "main"
ipkg   = "rhone-js.ipkg"

[db.rio]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-rio"
commit = "main"
ipkg   = "rio.ipkg"
test   = "test.ipkg"

[db.snocvect]
type   = "github"
url    = "https://github.com/mattpolzin/idris-snocvect"
commit = "main"
ipkg   = "snocvect.ipkg"

[db.sop]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-sop"
commit = "main"
ipkg   = "sop.ipkg"

[db.string-builder]
type   = "github"
url    = "https://github.com/Z-snails/string-builder"
commit = "main"
ipkg   = "string-builder.ipkg"
test   = "test/test.ipkg"

[db.summary-stat]
type   = "github"
url    = "https://github.com/buzden/idris2-summary-stat"
commit = "master"
ipkg   = "summary-stat.ipkg"
test   = "tests/tests.ipkg"

[db.tailrec]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-tailrec"
commit = "main"
ipkg   = "tailrec.ipkg"

[db.time-for-sleep]
type   = "github"
url    = "https://github.com/buzden/idris2-time-for-sleep"
commit = "master"
ipkg   = "time-for-sleep.ipkg"
test   = "tests/tests.ipkg"

[db.tester]
type   = "github"
url    = "https://github.com/cuddlefishie/tester-idr"
commit = "main"
ipkg   = "tester.ipkg"

[db.toml]
type   = "github"
url    = "https://github.com/cuddlefishie/toml-idr"
commit = "main"
ipkg   = "toml.ipkg"

[db.typelevel-emptiness-collections]
type   = "git"
url    = "https://github.com/buzden/idris2-typelevel-emptiness-collections"
commit = "master"
ipkg   = "typelevel-emptiness-collections.ipkg"
test   = "tests/tests.ipkg"

[db.node]
type = "github"
url  = "https://github.com/kbertalan/idris2-node"
commit = "main"
ipkg = "node.ipkg"

[db.promise]
type = "github"
url  = "https://github.com/kbertalan/idris2-promise"
commit = "main"
ipkg = "promise.ipkg"

[db.timeit]
type = "github"
url  = "https://github.com/MarcelineVQ/idris2-timeit"
commit = "main"
ipkg = "timeit.ipkg"

[db.tyttp]
type = "github"
url  = "https://github.com/kbertalan/tyttp"
commit = "main"
ipkg = "tyttp.ipkg"

[db.tyttp-json]
type = "github"
url  = "https://github.com/kbertalan/tyttp-json"
commit = "main"
ipkg = "tyttp-json.ipkg"

[db.xml]
type   = "github"
url    = "https://github.com/madman-bob/idris2-xml"
commit = "main"
ipkg   = "xml.ipkg"

[db.tyre]
type   = "github"
url    = "https://github.com/kasiaMarek/TyRE"
commit = "main"
ipkg   = "tyre.ipkg"

[db.distribution]
type   = "github"
url    = "https://github.com/idris-bayes/distribution"
commit = "main"
ipkg   = "distribution.ipkg"

[db.free]
type   = "github"
url    = "https://github.com/idris-bayes/free"
commit = "main"
ipkg   = "free.ipkg"

[db.log-domain]
type   = "github"
url    = "https://github.com/idris-bayes/log-domain"
commit = "main"
ipkg   = "log-domain.ipkg"

[db.monad-bayes]
type   = "github"
url    = "https://github.com/idris-bayes/monad-bayes"
commit = "main"
ipkg   = "monad-bayes.ipkg"

[db.url]
type   = "github"
url    = "https://github.com/running-grass/idris2-url"
commit = "main"
ipkg   = "url.ipkg"

[db.tls]
type   = "github"
url    = "https://github.com/octeep/idris2-tls"
commit = "master"
ipkg   = "tls.ipkg"

# [db.http]
# type   = "github"
# url    = "https://github.com/octeep/idris2-http"
# commit = "master"
# ipkg   = "http.ipkg"

# [db.prob-fx]
# type   = "github"
# url    = "https://github.com/idris-bayes/prob-fx"
# commit = "main"
# ipkg   = "prob-fx.ipkg"

[db.cheerio]
type   = "github"
url    = "https://github.com/running-grass/idris2-playground"
commit = "main"
ipkg   = "cheerio/cheerio.ipkg"

[db.matrix]
type   = "github"
url    = "https://github.com/running-grass/idris2-playground"
commit = "main"
ipkg   = "matrix/matrix.ipkg"

[db.game-2048]
type   = "github"
url    = "https://github.com/running-grass/idris2-playground"
commit = "main"
ipkg   = "game-2048/game-2048.ipkg"

[db.spidr]
type   = "github"
url    = "https://github.com/joelberkeley/spidr"
commit = "master"
ipkg   = "spidr.ipkg"

[db.uniplate]
type   = "github"
url    = "https://github.com/Z-snails/uniplate-idr"
commit = "main"
ipkg   = "uniplate.ipkg"

[db.utf8]
type   = "github"
url    = "https://git.sr.ht/~janus/utf8"
commit = "master"
ipkg   = "utf8.ipkg"
test   = "test/test.ipkg"

[db.webidl]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-webidl"
commit = "main"
ipkg   = "webidl.ipkg"

[db.idrisGL]
type   = "github"
url    = "https://github.com/ECburx/Idris2GL"
commit = "main"
ipkg   = "idrisGL.ipkg"

[db.c-ffi]
type   = "github"
url    = "https://github.com/joelberkeley/c-ffi"
commit = "master"
ipkg   = "c-ffi.ipkg"
test   = "test.ipkg"
