pack.commit = "latest:main"

[custom.all.pack-admin]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "latest:main"
ipkg   = "pack-admin.ipkg"

[custom.all.pack]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-pack"
commit = "latest:main"
ipkg   = "pack.ipkg"

[custom.all.ref1]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"

[custom.all.array]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-array"
commit = "latest:main"
ipkg   = "array.ipkg"

[custom.all.bytestring]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-bytestring"
commit = "latest:main"
ipkg   = "bytestring.ipkg"

[custom.all.algebra]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "latest:main"
ipkg   = "algebra.ipkg"

[custom.all.elab-util]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"

[custom.all.filepath]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-filepath"
commit = "latest:main"
ipkg   = "filepath.ipkg"

[custom.all.getopts]
type   = "github"
url    = "https://github.com/idris-community/idris2-getopts"
commit = "latest:main"
ipkg   = "getopts.ipkg"

[custom.all.ilex]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-ilex"
commit = "latest:main"
ipkg   = "ilex.ipkg"

[custom.all.ilex-core]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-ilex"
commit = "latest:main"
ipkg   = "core/ilex-core.ipkg"

[custom.all.ilex-toml]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-ilex"
commit = "latest:main"
ipkg   = "toml/ilex-toml.ipkg"

[custom.all.refined]
type   = "github"
url    = "https://github.com/stefan-hoeck/idris2-refined"
commit = "latest:main"
ipkg   = "refined.ipkg"
